// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsbxzqfyajgtwaivlzea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzYnh6cWZ5YWpndHdhaXZsemVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjU3MjQsImV4cCI6MjA2MDkwMTcyNH0.cSMj-quQAT3Ay1U-PdnP0z_3Vr013hPuBlxYn5vPEDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);